"""Complete service pages and navigation; content recovered from the owner's site."""
import json
from html import escape
from pathlib import Path


def register(g):
    t, img, icon, link = (g[k] for k in ('t', 'img', 'icon', 'link'))
    head, cta, pano, film = (g[k] for k in ('section_head', 'cta', 'pano', 'film_section'))
    models = json.loads((Path(__file__).parent / 'CAD3D-CONTENT-ASSETS.json').read_text())['models']
    catalogue = [
        ('architettura.html', ('Architettura e interni', 'Architecture and interiors'), ('Rendering di spazi, luce e materiali.', 'Rendering of space, light and materials.')),
        ('rinnovabili.html', ('Energie rinnovabili', 'Renewable energy'), ('Fotoinserimenti, impianti e presentazioni VR.', 'Photo insertions, plants and VR presentations.')),
        ('tour-virtuali.html', ('Tour virtuali e VR', 'Virtual tours and VR'), ('Sei esperienze da aprire e visitare.', 'Six experiences to open and explore.')),
        ('modellazione-3d.html', ('Modellazione 3D', '3D modelling'), ('Oggetti, arredi, componenti e gioielli.', 'Objects, furniture, components and jewellery.')),
        ('reverse-engineering.html', ('Reverse engineering', 'Reverse engineering'), ('Dall’oggetto alla geometria digitale.', 'From an object to digital geometry.')),
        ('panorami-360.html', ('Panorami fotografici 360°', '360° photographic panoramas'), ('Luoghi reali, esplorabili a distanza.', 'Real places, explored remotely.')),
        ('video-animazioni.html', ('Video e animazioni', 'Video and animation'), ('Percorsi, dettagli e progetto in movimento.', 'Journeys, details and projects in motion.')),
    ]
    cases = [
        ('Statkraft', ('Agrivoltaico a Leuth, Paesi Bassi', 'Agrivoltaics in Leuth, Netherlands'), ('Un tour fotografico per esplorare strutture, coltivazioni e contesto dell’impianto.', 'A photographic tour to explore the structures, crops and surroundings of the plant.'), 'https://www.cad3d.expert/leuthvt/'),
        ('Mazak', ('Stand fieristico', 'Exhibition stand'), ('Una visita dello stand che rende l’allestimento consultabile anche dopo la fiera.', 'A visit to the stand that keeps the exhibition accessible after the event.'), 'https://www.cad3d.expert/tourmazakemo/'),
        ('Valigeria Ambrosetti', ('Retail / Varese', 'Retail / Varese'), ('Un negozio da conoscere a distanza, attraverso i suoi ambienti e percorsi.', 'A shop to discover remotely through its spaces and pathways.'), 'https://www.valigeriaambrosetti.it/tourvirtuale/index.htm'),
        ('Deodato Arte', ('Galleria / Varese', 'Gallery / Varese'), ('La visita virtuale degli spazi espositivi della galleria.', 'A virtual visit to the gallery’s exhibition spaces.'), 'https://www.deodato.com/virtual/varese/'),
    ]
    demos = [
        ('Villa demo', ('Architettura in CGI', 'CGI architecture'), ('Una villa interamente virtuale, prima della costruzione.', 'An entirely virtual villa, before construction.'), 'https://www.cad3d.expert/villademo/'),
        ('Novazzano', ('Immobili / Tour fotografico', 'Property / Photographic tour'), ('Una visita agli ambienti di una villa esistente.', 'A visit to the spaces of an existing villa.'), 'https://www.cad3d.expert/novazzano/'),
    ] + [(name, kind, desc, url) for name, kind, desc, url in cases]

    def external(url, label):
        return f'<a class="text-link" href="{url}" target="_blank" rel="noopener">{label}{icon()}</a>'

    def opening(label, title, text):
        return f'<section class="page-opening wrap"><a class="back-link" href="servizi.html">{t("Tutti i servizi", "All services")}</a><p class="section-label">{label}</p><h1>{title}</h1><p class="opening-description">{text}</p></section>'

    def service_index():
        return '<div class="service-index">' + ''.join(f'<a href="{url}"><span>{t(*label)}</span><p>{t(*desc)}</p>{icon()}</a>' for url, label, desc in catalogue) + '</div>'

    def nav_link(url, label, filename):
        return f'<a href="{url}"'+(' aria-current="page"' if url == filename else '')+f'>{label}</a>'

    def navigation(filename):
        items=[('progetti.html', t('Progetti','Projects')), ('servizi.html',t('Servizi','Services')), ('tour-virtuali.html',t('Tour','Tours')), ('studio.html','Studio'),('contatti.html',t('Contatti','Contact'))]
        output=''
        for url,label in items:
            if url=='servizi.html':
                children=''.join(nav_link(u,t(*l),filename) for u,l,_ in catalogue)
                output += '<div class="nav-services">'+nav_link(url,label,filename)+f'<button class="services-toggle" aria-label="{t("Mostra tutti i servizi","Show all services")}" aria-expanded="false" aria-controls="services-menu">{icon("plus")}</button><div class="services-menu" id="services-menu" hidden>{children}<a href="servizi.html#formazione">{t("Formazione e consulenza AI","Training and AI consultancy")}</a><a href="servizi.html#fiere">{t("Fiere e showroom","Exhibitions and showrooms")}</a></div></div>'
            else: output+=nav_link(url,label,filename)
        return output

    def mobile_navigation(filename):
        main=[('index.html','Home'),('progetti.html',t('Progetti','Projects')),('servizi.html',t('Tutti i servizi','All services')),('referenze.html',t('Referenze','References')),('studio.html','Studio'),('contatti.html',t('Contatti','Contact'))]
        return '<div class="mobile-primary">'+''.join(nav_link(u,l,filename) for u,l in main)+'</div><div class="mobile-services"><p>'+t('Esplora i servizi','Explore the services')+'</p>'+''.join(nav_link(u,t(*l),filename) for u,l,_ in catalogue)+'<a href="servizi.html#formazione">'+t('Formazione e consulenza AI','Training and AI consultancy')+'</a></div>'

    def footer_navigation(filename):
        return '<div class="footer-service-index"><p>'+t('Servizi','Services')+'</p>'+''.join(nav_link(u,t(*l),filename) for u,l,_ in catalogue)+'</div><div class="footer-studio-index"><p>CAD3D.Expert</p>'+''.join(nav_link(u,t(*l),filename) for u,l in [('progetti.html',('Progetti','Projects')),('referenze.html',('Referenze','References')),('studio.html',('Studio','Studio')),('contatti.html',('Contatti','Contact')),('servizi.html#formazione',('Formazione e AI','Training and AI'))])+'</div>'

    def model_image(number, title, eager=False):
        m=models[number-1]; src=g['AS']+m['file']; w,h=m['dimensions']
        return f'<button class="model-image" data-image="{src}" data-title="{escape(title,quote=True)}" data-description="{t("Dalla galleria originale CAD3D.Expert.","From the original CAD3D.Expert gallery.")}" aria-label="{t("Ingrandisci: ","Enlarge: ")+escape(title,quote=True)}"><img src="{src}" width="{w}" height="{h}" alt="{escape(title,quote=True)}" loading="{"eager" if eager else "lazy"}" decoding="async"><span class="image-action">{icon("expand")}</span></button>'

    def model_title(number):
        if number in (13,16,18): return t('Oggetto originale', 'Original object')+f' / {number:02}'
        if 19<=number<=34 or number==36: return t('Gioiello / Modello 3D', 'Jewellery / 3D model')+f' {number:02}'
        if number==35 or number>=37: return t('Oggetto / Modello 3D', 'Object / 3D model')+f' {number:02}'
        return t('Modello CAD', 'CAD model')+f' {number:02}'

    def model_cards(numbers):
        return '<div class="model-grid">'+''.join('<article>'+model_image(n,model_title(n))+f'<h3>{model_title(n)}</h3></article>' for n in numbers)+'</div>'

    def modelling():
        selected=[1,6,8,14,18,28,31,36]
        return opening(t('Modellazione 3D','3D modelling'),t('Ogni forma.<br>Un modello da costruire.','Every shape.<br>A model to build.'),t('Dagli oggetti ai componenti, dagli arredi ai gioielli. Costruisco geometrie 3D a partire da disegni, misure e riferimenti, in funzione del risultato che ti serve.','From objects to components, furniture to jewellery. I build 3D geometry from drawings, measurements and references, according to the result you need.'))+f'<section class="wrap model-section" id="galleria">{head(t("La forma, da vicino.","The form, up close."),t("Una selezione dalla galleria originale. Tocca un’immagine per vederla completa; sotto trovi tutti i 40 esempi pubblicati.","A selection from the original gallery. Tap an image to see it in full; all 40 published examples are available below."))}{model_cards(selected)}<details class="model-archive"><summary>{t("Esplora la galleria completa · 40 immagini","Explore the full gallery · 40 images")}</summary>{model_cards([n for n in range(1,41) if n not in selected])}</details></section><section class="wrap detail-section">{head(t("La geometria segue<br>il tuo obiettivo.","Geometry follows<br>your goal."))}<div class="deliverables"><article><h3>{t("Oggetti e componenti","Objects and components")}</h3><p>{t("Geometrie e dettagli ricostruiti da disegni e misure. Struttura del modello e livello di dettaglio definiti prima di iniziare.","Geometry and details rebuilt from drawings and measurements. The model structure and level of detail are agreed before starting.")}</p></article><article><h3>{t("Arredi e prodotto","Furniture and products")}</h3><p>{t("Volumi, superfici e varianti da visualizzare nel loro insieme o nei dettagli, anche per render e animazioni.","Volumes, surfaces and variations to visualise as a whole or in detail, including for rendering and animation.")}</p></article><article><h3>{t("Gioielli e forme libere","Jewellery and freeform shapes")}</h3><p>{t("Superfici curve e forme organiche: dal riferimento iniziale alla geometria da sviluppare e presentare.","Curved surfaces and organic shapes: from the initial reference to geometry ready to develop and present.")}</p></article></div></section><section class="brief-section wrap"><h2>{t("Hai già un oggetto?","Already have an object?")}</h2><div><p>{t("Possiamo partire dalla sua forma e dalle informazioni disponibili per ricostruirlo in digitale.","We can start from its shape and the available information to rebuild it digitally.")}</p>{link("reverse-engineering.html","Reverse engineering","text-link")}</div></section>'+cta()

    def reverse():
        return opening('Reverse engineering',t('Dall’oggetto.<br>Al modello digitale.','From the object.<br>To the digital model.'),t('Ricostruire la geometria di un elemento esistente per svilupparla, modificarla o visualizzarla. Il punto di partenza è l’oggetto, insieme alle misure e ai riferimenti disponibili.','Rebuild the geometry of an existing element to develop, modify or visualise it. The starting point is the object, together with available measurements and references.'))+f'<section class="wrap reverse-example">{head(t("Reale e digitale.<br>La forma si ritrova.","Physical and digital.<br>The shape is rebuilt."),t("Fotografia e modello dello stesso componente, già presenti nella galleria originale CAD3D.Expert.","A photograph and model of the same component, already present in the original CAD3D.Expert gallery."))}<div class="reverse-pair"><figure>{model_image(13,t("Componente originale","Original component"))}<figcaption>{t("Oggetto originale","Original object")}</figcaption></figure><figure>{model_image(14,t("Geometria CAD ricostruita","Rebuilt CAD geometry"))}<figcaption>{t("Modello CAD","CAD model")}</figcaption></figure></div></section><section class="wrap method-section">{head(t("Un processo da definire<br>sul tuo componente.","A process defined<br>around your component."))}<div class="method-grid"><article><span>01</span><h3>{t("Raccogliere i riferimenti","Gather references")}</h3><p>{t("Oggetto, misure, fotografie, disegni o scansioni già disponibili. Concordiamo scala, zone da ricostruire e dettaglio necessario.","The object, measurements, photographs, drawings or existing scans. We agree on scale, areas to rebuild and required detail.")}</p></article><article><span>02</span><h3>{t("Ricostruire la geometria","Rebuild the geometry")}</h3><p>{t("Superfici e volumi prendono forma nel modello CAD. Condividiamo i passaggi utili a controllare proporzioni e interpretazione dei riferimenti.","Surfaces and volumes take shape in the CAD model. We share the steps needed to review proportions and the interpretation of references.")}</p></article><article><span>03</span><h3>{t("Preparare il modello","Prepare the model")}</h3><p>{t("Definiamo insieme formati, utilizzo e tolleranze richieste. Eventuali verifiche dimensionali e requisiti produttivi vanno concordati nel brief.","We agree on formats, intended use and required tolerances. Dimensional checks and manufacturing requirements are defined in the brief.")}</p></article></div></section><section class="brief-section wrap"><h2>{t("Partiamo dal tuo pezzo.","Start with your part.")}</h2><div><p>{t("Inviami alcune fotografie, le dimensioni principali e lo scopo del modello. Valutiamo quali informazioni servono per procedere.","Send a few photographs, the main dimensions and the purpose of the model. We’ll assess what information is needed to proceed.")}</p>{link("contatti.html",t("Descrivi il componente","Describe the component"),"text-link")}</div></section>'+cta()

    def panoramas():
        return opening(t('Panorami fotografici 360°','360° photographic panoramas'),t('Un luogo reale.<br>Tutto intorno a te.','A real place.<br>All around you.'),t('Fotografie sferiche per osservare un ambiente in ogni direzione. Per immobili, spazi commerciali, paesaggi e luoghi da conoscere prima di una visita.','Spherical photographs to view a space in every direction. For property, commercial spaces, landscapes and places to discover before visiting.'))+f'<section class="wrap panorama-demo-card"><div><span class="demo-number">360°</span><h2>{t("Prova il panorama fotografico.","Try the photographic panorama.")}</h2><p>{t("Apri la dimostrazione originale e sposta il punto di vista per esplorare la scena.","Open the original demonstration and move the viewpoint to explore the scene.")}</p>{external("https://www.cad3d.expert/street1",t("Apri la dimostrazione 360°","Open the 360° demonstration"))}</div><div class="panorama-demo-graphic" aria-hidden="true"><span>360°</span><svg viewBox="0 0 340 220" fill="none" stroke="currentColor"><ellipse cx="170" cy="110" rx="140" ry="74"/><ellipse cx="170" cy="110" rx="60" ry="74"/><path d="M30 110h280M58 67c65 30 159 30 224 0M58 153c65-30 159-30 224 0"/></svg></div></section><section class="wrap detail-section">{head(t("Una scena.<br>Una visita completa.","One scene.<br>A complete visit."))}<div class="two-columns"><article><h3>{t("Panorama fotografico","Photographic panorama")}</h3><p>{t("Un singolo punto di ripresa sferico documenta un luogo esistente. L’utente sceglie liberamente dove guardare.","A single spherical viewpoint documents an existing place. Visitors freely choose where to look.")}</p></article><article><h3>{t("Tour virtuale","Virtual tour")}</h3><p>{t("Più panorami collegati permettono di muoversi tra ambienti, con percorsi e punti informativi. I tour possono partire da fotografie o da un modello CGI.","Linked panoramas let visitors move between spaces, with routes and information points. Tours can be based on photographs or a CGI model.")}</p>{link("tour-virtuali.html#tour-esempi",t("Esplora i tour di esempio","Explore the example tours"),"text-link")}</article></div></section>'+cta()

    def videos():
        return opening(t('Video e animazioni','Video and animation'),t('Il progetto.<br>In movimento.','The project.<br>In motion.'),t('La camera accompagna lo sguardo: un percorso nello spazio, un dettaglio da osservare, un impianto da comprendere. Sequenze CGI per presentazioni, web e comunicazione.','The camera guides the eye: a journey through space, a detail to study, a plant to understand. CGI sequences for presentations, websites and communication.'))+film()+f'<section class="wrap detail-section">{head(t("Un percorso costruito<br>per raccontare.","A journey designed<br>to tell the story."))}<div class="deliverables"><article><h3>{t("Architettura e interni","Architecture and interiors")}</h3><p>{t("Movimenti di camera per leggere la distribuzione degli spazi, la luce e i materiali.","Camera movements to show the layout of spaces, lighting and materials.")}</p></article><article><h3>{t("Impianti e paesaggio","Plants and landscape")}</h3><p>{t("Viste d’insieme e percorsi per presentare la disposizione delle strutture e il loro rapporto con il sito.","Overviews and routes to present the layout of structures and their relationship with the site.")}</p></article><article><h3>{t("Oggetti e dettagli","Objects and details")}</h3><p>{t("Inquadrature ravvicinate e sequenze per mettere in evidenza forma, superfici e particolari.","Close-ups and sequences to highlight shape, surfaces and details.")}</p></article></div></section><section class="brief-section wrap"><h2>{t("Quale storia vuoi mostrare?","What story do you want to show?")}</h2><p>{t("Definiamo destinatari, durata, formato e percorso. Se il modello esiste già, lo valutiamo; altrimenti partiamo dalla modellazione.","We define audience, duration, format and camera route. If a model already exists, we review it; otherwise we start with modelling.")}</p></section>'+cta()

    def references():
        cards=''.join(f'<article><p class="section-label">{t(*kind)}</p><h2>{name}</h2><p>{t(*desc)}</p>{external(url,t("Apri il progetto","Open the project"))}</article>' for name,kind,desc,url in cases)
        return opening(t('Referenze','References'),t('Le esperienze.<br>I progetti pubblicati.','The experiences.<br>The published projects.'),t('Una selezione di visite virtuali pubblicate per energia, fiere, retail e arte. Ogni progetto si può aprire direttamente.','A selection of published virtual visits for energy, exhibitions, retail and art. Every project can be opened directly.'))+f'<section class="wrap reference-section"><div class="reference-grid">{cards}</div></section><section class="brief-section wrap"><h2>{t("Il tuo settore.<br>Il tuo prossimo progetto.","Your sector.<br>Your next project.")}</h2><p>{t("Collaboro con studi e aziende in Italia, Svizzera ed Europa. Se cerchi un esempio vicino alla tua esigenza, scrivimi: scegliamo insieme i riferimenti più utili.","I collaborate with practices and companies in Italy, Switzerland and Europe. If you need an example relevant to your project, get in touch and we’ll choose useful references together.")}</p></section>'+cta()

    def tour_cards():
        cards=''
        for n,(name,kind,desc,url) in enumerate(demos,1):
            media=img('villa',name,small=True) if n==1 else f'<div class="tour-type"><span class="demo-number">0{n}</span><span>{t(*kind)}</span>{icon("play")}</div>'
            cards+=f'<article class="tour-card"><a href="{url}" target="_blank" rel="noopener">{media}<h3>{name}</h3><p>{t(*desc)}</p><span class="text-link">{t("Apri il tour","Open the tour")}{icon()}</span></a></article>'
        return '<div class="tour-grid">'+cards+'</div>'

    def tours():
        return opening(t('Tour virtuali e VR','Virtual tours and VR'),t('La distanza<br>diventa presenza.','Distance<br>becomes presence.'),t('Luoghi reali e progetti ancora da costruire. Scegli una delle sei esperienze pubblicate o esplora qui sotto la villa virtuale a 360°.','Real places and projects yet to be built. Choose one of the six published experiences or explore the 360° virtual villa below.'))+f'<section class="wrap tour-examples" id="tour-esempi">{head(t("Scegli dove entrare.","Choose where to step inside."),t("Architettura, energia, retail, fiere e arte. I tour si aprono in una nuova scheda.","Architecture, energy, retail, exhibitions and art. Tours open in a new tab."))}{tour_cards()}<div class="tour-photography-link">{link("panorami-360.html",t("Cerchi la dimostrazione di panorami fotografici 360°?","Looking for the 360° photographic panorama demonstration?"),"text-link")}</div></section><section class="wrap tour-pano">{head(t("Dentro la villa virtuale.","Inside the virtual villa."),t("Due punti di vista CGI originali. Trascina per guardarti intorno o apri la visita completa.","Two original CGI viewpoints. Drag to look around or open the complete visit."))}{pano()}<div class="experience-bottom">{external("https://www.cad3d.expert/villademo/",t("Continua nel tour completo","Continue in the full tour"))}</div></section>{film()}<section class="wrap detail-section">{head(t("Fotografia e CGI.<br>Due punti di partenza.","Photography and CGI.<br>Two starting points."))}<div class="two-columns"><article><h3>{t("Tour fotografici","Photographic tours")}</h3><p>{t("Riprese sferiche di spazi esistenti, collegate per visitare immobili, musei, negozi, showroom e stand fieristici.","Spherical photographs of existing spaces, linked to visit properties, museums, shops, showrooms and exhibition stands.")}</p>{link("panorami-360.html",t("Panorami fotografici 360°","360° photographic panoramas"),"text-link")}</article><article><h3>{t("Tour in computer grafica","Computer-generated tours")}</h3><p>{t("Un modello 3D diventa un luogo da esplorare: distribuzione, materiali e atmosfera di un edificio o di un impianto ancora in progetto.","A 3D model becomes a place to explore: the layout, materials and atmosphere of a building or plant still at the design stage.")}</p>{link("rinnovabili.html#vr",t("Presentazioni VR per le rinnovabili","VR presentations for renewables"),"text-link")}</article></div></section>'+cta()

    old_services=g['services']
    def services():
        body=old_services(); start=body.index('<section class="capabilities-section');body=body[:start]
        return body+f'<section class="wrap complete-services">{head(t("Tutte le competenze.<br>Il percorso giusto.","All the expertise.<br>The right path."),t("Ogni servizio ha uno spazio dedicato: esempi, processo e materiali da cui partire.","Every service has its own page: examples, process and starting materials."))}{service_index()}</section><section class="wrap detail-section" id="fiere">{head(t("Fiere e showroom.<br>Una visita che continua.","Exhibitions and showrooms.<br>A visit that continues."),t("Lo spazio espositivo rimane visitabile anche dopo l’evento. Tour fotografici per mostrare stand, allestimenti e ambienti commerciali.","The exhibition space remains accessible after the event. Photographic tours to show stands, displays and commercial interiors."))}<div class="two-columns"><article><h3>Mazak</h3><p>{t("Il tour dello stand fieristico, pubblicato nel portfolio originale.","The exhibition stand tour, published in the original portfolio.")}</p>{external(cases[1][3],t("Visita lo stand","Visit the stand"))}</article><article><h3>{t("Retail e gallerie","Retail and galleries")}</h3><p>{t("Valigeria Ambrosetti e Deodato Arte: due esempi di ambienti da esplorare a distanza.","Valigeria Ambrosetti and Deodato Arte: two examples of spaces to explore remotely.")}</p>{link("referenze.html",t("Esplora le referenze","Explore the references"),"text-link")}</article></div></section><section class="brief-section wrap" id="formazione"><h2>{t("Formazione.<br>E consulenza AI.","Training.<br>And AI consultancy.")}</h2><div><p>{t("Un affiancamento dedicato per integrare modellazione, visualizzazione e strumenti AI nel tuo lavoro. Partiamo dal tuo flusso, dalle competenze e dagli obiettivi da sviluppare.","Dedicated support to integrate modelling, visualisation and AI tools into your work. We start from your workflow, skills and development goals.")}</p>{link("contatti.html",t("Parliamo del tuo percorso","Let’s discuss your path"),"text-link")}</div></section>'+cta()

    old_energy=g['energy']
    def energy():
        body=old_energy(); vr=f'<section class="wrap vr-section" id="vr">{head(t("Il progetto si visita.<br>Anche in realtà virtuale.","Visit the project.<br>In virtual reality too."),t("Un’esperienza dedicata per presentare impianti a investitori, comunità e visitatori di eventi e fiere.","A dedicated experience to present plants to investors, communities and visitors at events and exhibitions."))}<div class="deliverables"><article><h3>Meta Quest 3</h3><p>{t("Esplorazione immersiva del progetto con il visore, per osservare spazi e strutture da un punto di vista coinvolgente.","Immersive exploration of the project with the headset, to view spaces and structures from an engaging perspective.")}</p></article><article><h3>{t("Diretta su maxi monitor","Live view on large screens")}</h3><p>{t("Il punto di vista del visitatore nel visore può essere trasmesso dal vivo su uno schermo, per condividere l’esperienza con il pubblico.","The visitor’s headset viewpoint can be shown live on a screen, sharing the experience with the audience.")}</p></article><article><h3>{t("Modelli georeferenziati","Georeferenced models")}</h3><p>{t("Impianti personalizzati di fotovoltaico, agrivoltaico, eolico e BESS, inseriti nel contesto geografico del progetto.","Custom photovoltaic, agrivoltaic, wind and BESS plants placed in the project’s geographical context.")}</p></article></div><div class="section-end">{link("contatti.html",t("Progettiamo la presentazione VR","Plan your VR presentation"),"text-link")}</div></section>'
        return body.replace(cta(),vr+cta())

    old_home=g['home']
    def home():
        body=old_home()
        return body.replace(film(),f'<section class="wrap home-service-map"><p class="section-label">{t("Esplora tutti i servizi","Explore all services")}</p>{service_index()}</section>'+film()).replace('<section class="method-section',f'<section class="wrap home-reference-link"><div><h2>{t("Esperienze già pubblicate.","Published experiences.")}</h2><p>{t("Energia, fiere, retail e arte: apri i progetti e scopri le visite virtuali.","Energy, exhibitions, retail and art: open the projects and discover the virtual visits.")}</p></div><div>{link("tour-virtuali.html#tour-esempi",t("Sei tour da esplorare","Six tours to explore"),"text-link")}{link("referenze.html",t("Referenze","References"),"text-link")}</div></section><section class="method-section')

    old_projects=g['projects']
    def projects():
        body=old_projects(); marker='<div class="portfolio-note">'
        return body.replace(marker,f'<div class="portfolio-additional"><h2>{t("Oggetti, componenti e gioielli.","Objects, components and jewellery.")}</h2><p>{t("La modellazione ha una galleria dedicata, con 40 immagini dal portfolio originale.","Modelling has its own gallery, with 40 images from the original portfolio.")}</p>{link("modellazione-3d.html#galleria",t("Esplora la modellazione 3D","Explore 3D modelling"),"text-link")}</div>'+marker)

    new_pages={
        'modellazione-3d.html':(modelling,('Modellazione 3D e galleria','3D modelling and gallery')),
        'reverse-engineering.html':(reverse,('Reverse engineering','Reverse engineering')),
        'panorami-360.html':(panoramas,('Panorami fotografici 360°','360° photographic panoramas')),
        'video-animazioni.html':(videos,('Video e animazioni 3D','3D video and animation')),
        'referenze.html':(references,('Referenze e progetti pubblicati','References and published projects')),
    }
    for filename, fn in [('index.html',home),('progetti.html',projects),('servizi.html',services),('rinnovabili.html',energy),('tour-virtuali.html',tours)]:
        g['PAGES'][filename]=(fn,g['PAGES'][filename][1])
    g['PAGES'].update(new_pages)
    g.update(navigation=navigation,mobile_navigation=mobile_navigation,footer_navigation=footer_navigation)
